// Auto-extracted Mixin
'use strict';
const { TokenType } = require('../constants');
module.exports = {
  _init(tokens, target = 'node') {
    this.tokens = tokens;
    this.target = target;

    this.pos = 0;
    this.indent = 0;

    /** @type {string[]} Pre-allocate output array for better performance */
    this.output = [];
    // Estimate output size: ~3 lines per token on average
    const estimatedLines = Math.floor(tokens.length * 3);
    if (estimatedLines > 100) {
      this.output = new Array(estimatedLines);
      this.output.length = 0;
    }

    /** @type {Array<{line: number, message: string, column: number}>} */
    this.errors = [];

    /** @type {Set<string>} Global SHARED variables */
    this.scopes = [new Set()];
    this.sharedVars = new Set();

    /** @type {string[]} DATA statement values */
    this.dataValues = [];

    /** @type {string|null} Name of function currently being parsed */
    this.currentFunction = null;

    /** @type {Set<string>} Collected labels for GOTO/GOSUB support */
    this.labels = new Set();

    /** @type {Map<string, string[]>} Label code blocks for GOTO state machine */
    this.labelBlocks = new Map();

    // Performance optimization: Cache frequently accessed token properties
    this._cachedPeek = null;
    this._cachedPeekPos = -1;
  },

  parse() {
    // Pre-pass: Collect all DATA values first
    // This is necessary because DATA statements can appear anywhere in QBasic
    // but must be available for READ statements from the start
    this._collectDataValues();

    this._emitHeader();

    while (!this._isEnd()) {
      this._skipNewlines();
      if (this._isEnd()) break;

      try {
        this._parseStatement();
      } catch (e) {
        this._recordError(e.message);
        this._sync();
      }
    }

    this._emitFooter();
    return this.output.join('\n');
  },

  get currentVars() {
    return this.scopes[this.scopes.length - 1];
  },

  _addVar(name) {
    this.currentVars.add(name);
  },

  _hasVar(name) {
    // Check current scope first
    if (this.currentVars.has(name)) return true;

    // If in global scope (depth 1), no upper scopes to check
    if (this.scopes.length === 1) return false;

    // If in SUB/FUNCTION, only access global variables if they are SHARED
    return this.sharedVars.has(name);
  },

  _enterScope() {
    this.scopes.push(new Set());
  },

  _exitScope() {
    this.scopes.pop();
  },

  _collectDataValues() {
    const savedPos = this.pos;

    while (!this._isEnd()) {
      // Collect labels for GOTO/GOSUB support
      if (this._check(TokenType.IDENTIFIER)) {
        const next = this.tokens[this.pos + 1];
        if (next?.type === TokenType.PUNCTUATION && next?.value === ':') {
          this.labels.add(this._peek().value);
        }
      }

      if (this._matchKw('DATA')) {
        do {
          let val = '0';
          if (this._check(TokenType.STRING)) val = `"${this._advance().value}"`;
          else if (this._check(TokenType.NUMBER)) val = this._advance().value;
          else if (this._check(TokenType.IDENTIFIER))
            val = `"${this._advance().value}"`;
          else if (!this._isStmtEnd()) this._advance();
          else break;
          this.dataValues.push(val);
        } while (this._matchPunc(','));
      } else {
        this._advance();
      }
    }

    // Reset position for main pass
    this.pos = savedPos;
  },

  _recordError(msg) {
    const tok = this._peek();
    this.errors.push({
      line: (tok?.line || 1) - 1,
      message: msg,
      column: tok?.col || 0,
    });
  },

  _sync() {
    this._advance();
    while (!this._isEnd()) {
      if (this._prev()?.type === TokenType.NEWLINE) return;
      if (this._check(TokenType.KEYWORD)) return;
      this._advance();
    }
  },

  _emit(code) {
    this.output.push('  '.repeat(this.indent) + code);
  },

  _emitHeader() {
    this.output.push(`// Generated by QBasic Nexus
'use strict';
`);

    // Runtime environment abstraction
    if (this.target === 'node') {
      this.output.push(`
const readline = require('readline');
const { spawn } = require('child_process');
const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
  terminal: process.stdin.isTTY || false,
  crlfDelay: Infinity,
});

function _print(text, newline) {
  if (newline) console.log(text);
  else process.stdout.write(String(text));
}

function _input(prompt) {
  return new Promise(resolve => {
    if (rl.terminal === false || !process.stdin.isTTY) {
      process.stdout.write(prompt || '');
    }
    rl.question(prompt || '', answer => resolve(answer));
  });
}

function _cls() {
  console.clear();
}
`);
    } else if (this.target === 'web') {
      this.output.push(`
// Web Runtime Environment (Optimized v1.1.0)
// Safe runtime reference — works in both browser and Node.js (pkg)
const _runtime = (typeof globalThis !== 'undefined' && globalThis.runtime) ? globalThis.runtime
               : (typeof window   !== 'undefined' && window.runtime)       ? window.runtime
               : {};
const _print = _runtime.print || console.log;
const _input = _runtime.input || (typeof prompt !== 'undefined' ? prompt : (() => ''));
const _cls = _runtime.cls || console.clear;
const _locate = _runtime.locate || (() => {});
const _color = _runtime.color || (() => {});
const _beep = _runtime.beep || (() => {});
const _sound = _runtime.sound || (() => {});
const _play = _runtime.play || (() => {});
const _screen = _runtime.screen || (() => {});
const _width = _runtime.width || (() => {});
const _pset = _runtime.pset || (() => {});
const _preset = _runtime.preset || (() => {});
const _line = _runtime.line || (() => {});
const _circle = _runtime.circle || (() => {});
const _get = _runtime.get || (() => {});
const _put = _runtime.put || (() => {});
const _mouseinput = _runtime.mouseinput || (() => 0);
const _mousex = _runtime.mousex || (() => 0);
const _mousey = _runtime.mousey || (() => 0);
const _mousebutton = _runtime.mousebutton || (() => 0);
const _timer = _runtime.timer || (() => Date.now() / 1000);

// Advanced Image Functions
const _LOADIMAGE = _runtime.loadimage || (() => -1);
const _NEWIMAGE = _runtime.newimage || (() => -1);
const _COPYIMAGE = _runtime.copyimage || (() => -1);
const _FREEIMAGE = _runtime.freeimage || (() => {});
const _PUTIMAGE = _runtime.putimage || (() => {});
const _PRINTSTRING = _runtime.printstring || (() => {});

// Advanced Mouse Functions
const _MOUSEWHEEL = _runtime.mousewheel || (() => 0);
const _MOUSEHIDE = _runtime.mousehide || (() => {});
const _MOUSESHOW = _runtime.mouseshow || (() => {});

// Advanced Keyboard Functions
const _KEYDOWN = _runtime.keydown || (() => 0);
const _KEYHIT = _runtime.keyhit || (() => 0);
const _KEYCLEAR = _runtime.keyclear || (() => {});

// Advanced Sound Functions
const _SNDOPEN = _runtime.sndopen || (() => -1);
const _SNDPLAY = _runtime.sndplay || (() => {});
const _SNDLOOP = _runtime.sndloop || (() => {});
const _SNDCLOSE = _runtime.sndclose || (() => {});

// RGB Color Functions
const _RGB32 = _runtime.rgb32 || ((r, g, b, a) => ((a||255) << 24) | (r << 16) | (g << 8) | b);
const _RGBA32 = _runtime.rgba32 || _RGB32;
const _RED32 = _runtime.red32 || ((c) => (c >> 16) & 0xFF);
const _GREEN32 = _runtime.green32 || ((c) => (c >> 8) & 0xFF);
const _BLUE32 = _runtime.blue32 || ((c) => c & 0xFF);
const _ALPHA32 = _runtime.alpha32 || ((c) => (c >> 24) & 0xFF);

// Performance Functions
const _LIMIT = _runtime.limit || (async () => {});
const _DISPLAY = _runtime.display || (() => {});

// Advanced Math Functions
const _CEIL = _runtime.ceil || Math.ceil;
const _ROUND = _runtime.round || Math.round;
const _HYPOT = _runtime.hypot || Math.hypot;
const _D2R = _runtime.d2r || ((d) => d * (Math.PI / 180));
const _R2D = _runtime.r2d || ((r) => r * (180 / Math.PI));

// Extended Math Functions (from qbjs-main)
const _ACOS = _runtime.acos || Math.acos;
const _ASIN = _runtime.asin || Math.asin;
const _ATAN2 = _runtime.atan2 || Math.atan2;
const _FIX = _runtime.fix || ((x) => x < 0 ? Math.ceil(x) : Math.floor(x));
const _SGN = _runtime.sgn || ((x) => x > 0 ? 1 : x < 0 ? -1 : 0);

// String Functions (for convenience)
const _INSTR = _runtime.instr || ((a, b, c) => {
  let start = 1, source, search;
  if (c !== undefined) { start = a; source = String(b); search = String(c); }
  else { source = String(a); search = String(b); }
  const idx = source.indexOf(search, start - 1);
  return idx < 0 ? 0 : idx + 1;
});

// System Functions
const _DESKTOPWIDTH = _runtime.desktopwidth || (() => (typeof screen !== 'undefined' ? screen.width : 1920));
const _DESKTOPHEIGHT = _runtime.desktopheight || (() => (typeof screen !== 'undefined' ? screen.height : 1080));
const _PAINT = _runtime.paint || (() => {});

// Frame rate limiter (legacy)
let _lastLimitTime = Date.now();
async function _limit(fps) {
  const frameTime = 1000 / fps;
  const elapsed = Date.now() - _lastLimitTime;
  if (elapsed < frameTime) {
    await new Promise(r => setTimeout(r, frameTime - elapsed));
  }
  _lastLimitTime = Date.now();
}
`);
    }

    this.output.push(`
function _sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

// Helper for multi-dimensional arrays
function _makeArray(init, ...dims) {
   if (dims.length === 0) return init;
   const size = dims[0];
   const rest = dims.slice(1);
   return Array.from({length: size + 1}, () => _makeArray(init, ...rest));
}

// Screen position tracking (for LOCATE)
let _cursorRow = 1, _cursorCol = 1;
`);
    // Node.js specific I/O functions
    if (this.target === 'node') {
      this.output.push(`
function _locate(row, col) {
  _cursorRow = row;
  _cursorCol = col;
  if (typeof process !== 'undefined' && process.stdout?.write) {
    process.stdout.write(\`\\x1b[\${row};\${col}H\`);
  }
}

function _color(fg, bg) {
  const colors = [0, 12, 10, 14, 9, 13, 11, 7, 8, 12, 10, 14, 9, 13, 11, 15];
  if (typeof process !== 'undefined' && process.stdout?.write) {
    const ansiFg = colors[fg % 16] || 7;
    const ansiBg = colors[bg % 16] || 0;
    process.stdout.write(\`\\x1b[38;5;\${ansiFg}m\\x1b[48;5;\${ansiBg}m\`);
  }
}

const _beep = () => _sound(800, 1.82); // Standard BEEP: 800Hz, ~100ms

// High-performance cross-platform sound implementation
// Uses native OS features for fastest possible audio playback
function _sound(freq, duration) {
  // Clamp and validate values
  freq = Math.max(37, Math.min(32767, freq || 800));
  const qbDuration = Math.max(0.01, duration || 1);
  const ms = Math.floor((qbDuration / 18.2) * 1000);
  if (ms <= 0) return Promise.resolve();

  return new Promise(resolve => {
    const timeout = setTimeout(resolve, ms + 100); // Safety timeout
    
    if (process.platform === 'win32') {
      // Windows: Use mshta for instant JavaScript audio (much faster than PowerShell)
      // mshta is pre-installed on all Windows versions and starts instantly
      const jsCode = \`
        var ctx = new (window.AudioContext || window.webkitAudioContext)();
        var osc = ctx.createOscillator();
        var gain = ctx.createGain();
        osc.type = 'square';
        osc.frequency.value = \${Math.floor(freq)};
        gain.gain.setValueAtTime(0, ctx.currentTime);
        gain.gain.linearRampToValueAtTime(0.15, ctx.currentTime + 0.005);
        osc.connect(gain);
        gain.connect(ctx.destination);
        osc.start();
        setTimeout(function() { 
          gain.gain.linearRampToValueAtTime(0, ctx.currentTime + 0.01);
          setTimeout(function() { window.close(); }, 20); 
        }, \${ms});
      \`;
      
      const mshta = spawn('mshta', [
        \`javascript:var d=document;d.write('<html><head><script>\${jsCode.replace(/\\n/g, '')}</script></head></html>');d.close();\`
      ], { 
        detached: true, 
        stdio: 'ignore',
        windowsHide: true 
      });
      
      mshta.unref();
      mshta.on('error', () => {
        // Fallback to system bell
        process.stdout.write('\\x07');
        clearTimeout(timeout);
        resolve();
      });
      
      // Don't wait for mshta - it handles its own timing
      setTimeout(() => {
        clearTimeout(timeout);
        resolve();
      }, ms);
      
    } else if (process.platform === 'darwin') {
      // macOS: Use afplay with system sounds or sox if available
      // First try sox for frequency control, then fallback to system beep
      const sox = spawn('play', ['-n', 'synth', (ms/1000).toString(), 'square', freq.toString()], {
        stdio: 'ignore'
      });
      
      sox.on('error', () => {
        // sox not available, use system beep
        process.stdout.write('\\x07');
        clearTimeout(timeout);
        setTimeout(resolve, ms);
      });
      
      sox.on('close', () => {
        clearTimeout(timeout);
        resolve();
      });
      
    } else {
      // Linux: Try multiple methods in order of preference
      // 1. paplay with generated audio (PulseAudio)
      // 2. beep command
      // 3. System bell
      
      const beep = spawn('beep', ['-f', freq.toString(), '-l', ms.toString()], {
        stdio: 'ignore'
      });
      
      beep.on('error', () => {
        // beep not available, try speaker-test briefly or fall back to bell
        process.stdout.write('\\x07');
        clearTimeout(timeout);
        setTimeout(resolve, ms);
      });
      
      beep.on('close', (code) => {
        clearTimeout(timeout);
        if (code !== 0) {
          process.stdout.write('\\x07');
          setTimeout(resolve, ms);
        } else {
          resolve();
        }
      });
    }
  });
}
`);
    }

    this.output.push(`
const _DATA = [${this.dataValues.join(', ')}];
let _DATA_PTR = 0;

function _read() {
  if (_DATA_PTR >= _DATA.length) throw new Error("Out of DATA");
  return _DATA[_DATA_PTR++];
}

function _restore() {
  _DATA_PTR = 0;
}

// Random number generator with seeding support
let _rndSeed = Date.now();
function _randomize(seed) {
  _rndSeed = seed !== undefined ? seed : Date.now();
}
function _rnd() {
  _rndSeed = (_rndSeed * 9301 + 49297) % 233280;
  return _rndSeed / 233280;
}
`);

    // Screen/Width stubs - only for Node.js (web has them from runtime)
    if (this.target === 'node') {
      this.output.push(`
// Safe cross-environment runtime reference (Node.js / pkg)
const _runtime = (typeof globalThis !== 'undefined' && globalThis.runtime) ? globalThis.runtime
               : (typeof window   !== 'undefined' && window.runtime)       ? window.runtime
               : {};

// Screen mode (stub)
let _screenMode = 0;
function _screen(mode) {
  _screenMode = mode;
}

// Width (stub)
let _screenWidth = 80, _screenHeight = 25;
function _width(cols, rows) {
  _screenWidth = cols;
  _screenHeight = rows || 25;
}
`);
    }

    // Common code for both targets
    this.output.push(`

// INKEY$ support
let _inkeyBuffer = '';
function INKEY() {
  if (typeof _runtime['inkey$'] === 'function') {
      return _runtime['inkey$']();
  }
  const key = _inkeyBuffer;
  _inkeyBuffer = '';
  return key;
}

// File I/O (stubs for web compatibility)
const _files = {};
let _nextFileNum = 1;

// Mapped to runtime if available
const _openFunc = _runtime.open || (() => {});
const _closeFunc = _runtime.close || (() => {});
const _printFileFunc = _runtime.printFile || (() => {});
const _inputFileFunc = _runtime.inputFile || (() => {});

async function _open(filename, mode, filenum) {
  if (_runtime.open) {
      await _openFunc(filename, mode, filenum);
      return;
  }
  _files[filenum] = { filename, mode, data: '', pos: 0, eof: false };
}

async function _close(filenum) {
  if (_runtime.close) {
      await _closeFunc(filenum);
      return;
  }
  delete _files[filenum];
}

async function _closeAll() {
  // If runtime supports closeAll
  for (const f in _files) delete _files[f];
}

// INSTR function with proper 1-based index
function INSTR(start, str, find) {
  if (find === undefined) {
    find = str;
    str = start;
    start = 1;
  }
  const idx = str.indexOf(find, start - 1);
  return idx >= 0 ? idx + 1 : 0;
}

// TRUE/FALSE constants
const TRUE = -1;
const FALSE = 0;

(async () => {
try {
`);
  },

  _emitFooter() {
    this.output.push(`
} catch (e) {
  if (e === "__END__" || e === "STOP") {
    // Normal program termination — do nothing, fall through to finally
  } else if (typeof e === 'string' && e.startsWith('GOTO_')) {
    // GOTO jumped out of main body — normal for top-level GOTOs
  } else if (e && e.message) {
    process.stderr.write('\\nRuntime Error: ' + e.message + '\\n');
    if (typeof _runtime !== 'undefined' && typeof _runtime.error === 'function') {
      _runtime.error(e.message);
    }
  } else if (e !== undefined && e !== null) {
    process.stderr.write('\\nError: ' + String(e) + '\\n');
  }
} finally {
  ${
    this.target === 'node'
      ? `
  // Flush stdout before exit
  if (process.stdout.write('')) {
    rl.close();
    process.exit(0);
  } else {
    process.stdout.once('drain', () => { rl.close(); process.exit(0); });
  }`
      : ''
  }
}
})();
`);
  },

  _matchPunc(c) {
    const t = this._peek();
    if (t?.type === TokenType.PUNCTUATION && t.value === c) {
      this._advance();
      return true;
    }
    return false;
  },

  _consume(type) {
    if (this._check(type)) return this._advance();
    return null;
  },

  _consumeKw(kw) {
    this._matchKw(kw);
  },

  _consumeOp(op) {
    this._matchOp(op);
  },

  _consumeToken() {
    if (this._isEnd()) {
      const lastToken = this._prev();
      return {
        type: 'EOF',
        value: '',
        line: lastToken?.line || 1,
        col: lastToken?.col || 0,
      };
    }
    const token = this._advance();
    return (
      token || {
        type: 'UNKNOWN',
        value: '',
        line: this._prev()?.line || 1,
        col: 0,
      }
    );
  },

  _decIndent() {
    this.indent = Math.max(0, this.indent - 1);
  },

  _matchKw(kw) {
    if (this._checkKw(kw)) {
      this._advance();
      return true;
    }
    return false;
  },

  _checkKw(kw) {
    const t = this._peek();
    return t?.type === TokenType.KEYWORD && t.value === kw;
  },

  _advance() {
    if (!this._isEnd()) {
      this.pos++;
      // Invalidate cache
      this._cachedPeekPos = -1;
    }
    return this._prev();
  },

  _isEnd() {
    return this._check(TokenType.EOF);
  },

  _skipNewlines() {
    while (this._check(TokenType.NEWLINE)) this._advance();
  },

  _isStmtEnd() {
    const t = this._peek();
    if (!t || t.type === TokenType.EOF || t.type === TokenType.NEWLINE)
      return true;
    if (
      t.type === TokenType.KEYWORD &&
      ['THEN', 'ELSE', 'ELSEIF'].includes(t.value)
    )
      return true;
    return false;
  },

  _skipToEndOfLine() {
    while (!this._isStmtEnd() && !this._isEnd()) {
      this._advance();
    }
  },

  _check(type) {
    return this._peek()?.type === type;
  },

  _matchOp(op) {
    const t = this._peek();
    if (t?.type === TokenType.OPERATOR && t.value === op) {
      this._advance();
      return true;
    }
    return false;
  },

  _peek() {
    if (this._cachedPeekPos === this.pos) {
      return this._cachedPeek;
    }
    this._cachedPeek = this.tokens[this.pos] || null;
    this._cachedPeekPos = this.pos;
    return this._cachedPeek;
  },

  _prev() {
    return this.pos > 0 ? this.tokens[this.pos - 1] : null;
  },
};
